/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.reusable_components.tables;


import fi.hsl.jore.jore4.jooq.reusable_components.Keys;
import fi.hsl.jore.jore4.jooq.reusable_components.ReusableComponents;
import fi.hsl.jore.jore4.jooq.reusable_components.tables.records.VehicleSubmodeRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * The vehicle submode, which may have implications on which infrastructure 
 * links the vehicle can traverse
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VehicleSubmode extends TableImpl<VehicleSubmodeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>reusable_components.vehicle_submode</code>
     */
    public static final VehicleSubmode VEHICLE_SUBMODE = new VehicleSubmode();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VehicleSubmodeRecord> getRecordType() {
        return VehicleSubmodeRecord.class;
    }

    /**
     * The column <code>reusable_components.vehicle_submode.vehicle_submode</code>. The vehicle submode, which may have implications on which infrastructure links the vehicle can traverse
     */
    public final TableField<VehicleSubmodeRecord, String> VEHICLE_SUBMODE_ = createField(DSL.name("vehicle_submode"), SQLDataType.CLOB.nullable(false), this, "The vehicle submode, which may have implications on which infrastructure links the vehicle can traverse");

    /**
     * The column <code>reusable_components.vehicle_submode.belonging_to_vehicle_mode</code>. The vehicle mode the vehicle submode belongs to: https://www.transmodel-cen.eu/model/index.htm?goto=1:6:1:283
     */
    public final TableField<VehicleSubmodeRecord, String> BELONGING_TO_VEHICLE_MODE = createField(DSL.name("belonging_to_vehicle_mode"), SQLDataType.CLOB.nullable(false), this, "The vehicle mode the vehicle submode belongs to: https://www.transmodel-cen.eu/model/index.htm?goto=1:6:1:283");

    private VehicleSubmode(Name alias, Table<VehicleSubmodeRecord> aliased) {
        this(alias, aliased, null);
    }

    private VehicleSubmode(Name alias, Table<VehicleSubmodeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("The vehicle submode, which may have implications on which infrastructure links the vehicle can traverse"), TableOptions.table());
    }

    /**
     * Create an aliased <code>reusable_components.vehicle_submode</code> table reference
     */
    public VehicleSubmode(String alias) {
        this(DSL.name(alias), VEHICLE_SUBMODE);
    }

    /**
     * Create an aliased <code>reusable_components.vehicle_submode</code> table reference
     */
    public VehicleSubmode(Name alias) {
        this(alias, VEHICLE_SUBMODE);
    }

    /**
     * Create a <code>reusable_components.vehicle_submode</code> table reference
     */
    public VehicleSubmode() {
        this(DSL.name("vehicle_submode"), null);
    }

    public <O extends Record> VehicleSubmode(Table<O> child, ForeignKey<O, VehicleSubmodeRecord> key) {
        super(child, key, VEHICLE_SUBMODE);
    }

    @Override
    public Schema getSchema() {
        return ReusableComponents.REUSABLE_COMPONENTS;
    }

    @Override
    public UniqueKey<VehicleSubmodeRecord> getPrimaryKey() {
        return Keys.VEHICLE_SUBMODE_PKEY;
    }

    @Override
    public List<UniqueKey<VehicleSubmodeRecord>> getKeys() {
        return Arrays.<UniqueKey<VehicleSubmodeRecord>>asList(Keys.VEHICLE_SUBMODE_PKEY);
    }

    @Override
    public List<ForeignKey<VehicleSubmodeRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<VehicleSubmodeRecord, ?>>asList(Keys.VEHICLE_SUBMODE__VEHICLE_SUBMODE_BELONGING_TO_VEHICLE_MODE_FKEY);
    }

    private transient VehicleMode _vehicleMode;

    public VehicleMode vehicleMode() {
        if (_vehicleMode == null)
            _vehicleMode = new VehicleMode(this, Keys.VEHICLE_SUBMODE__VEHICLE_SUBMODE_BELONGING_TO_VEHICLE_MODE_FKEY);

        return _vehicleMode;
    }

    @Override
    public VehicleSubmode as(String alias) {
        return new VehicleSubmode(DSL.name(alias), this);
    }

    @Override
    public VehicleSubmode as(Name alias) {
        return new VehicleSubmode(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VehicleSubmode rename(String name) {
        return new VehicleSubmode(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VehicleSubmode rename(Name name) {
        return new VehicleSubmode(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
