/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.deleted.tables;


import fi.hsl.jore.jore4.jooq.deleted.Deleted;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * The routes from Transmodel:
 * https://www.transmodel-cen.eu/model/index.htm?goto=2:1:3:483
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Route_1637329168554 extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>deleted.route_1637329168554</code>
     */
    public static final Route_1637329168554 ROUTE_1637329168554 = new Route_1637329168554();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>deleted.route_1637329168554.route_id</code>. The ID of
     * the route.
     */
    public final TableField<Record, UUID> ROUTE_ID = createField(DSL.name("route_id"), SQLDataType.UUID, this, "The ID of the route.");

    /**
     * The column <code>deleted.route_1637329168554.description_i18n</code>. The
     * description of the route in the form of starting location - destination.
     * Placeholder for multilingual strings.
     */
    public final TableField<Record, String> DESCRIPTION_I18N = createField(DSL.name("description_i18n"), SQLDataType.CLOB, this, "The description of the route in the form of starting location - destination. Placeholder for multilingual strings.");

    /**
     * The column
     * <code>deleted.route_1637329168554.starts_from_scheduled_stop_point_id</code>.
     * The scheduled stop point where the route starts from.
     */
    public final TableField<Record, UUID> STARTS_FROM_SCHEDULED_STOP_POINT_ID = createField(DSL.name("starts_from_scheduled_stop_point_id"), SQLDataType.UUID, this, "The scheduled stop point where the route starts from.");

    /**
     * The column
     * <code>deleted.route_1637329168554.ends_at_scheduled_stop_point_id</code>.
     * The scheduled stop point where the route ends at.
     */
    public final TableField<Record, UUID> ENDS_AT_SCHEDULED_STOP_POINT_ID = createField(DSL.name("ends_at_scheduled_stop_point_id"), SQLDataType.UUID, this, "The scheduled stop point where the route ends at.");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public final TableField<Record, Object> ROUTE_SHAPE = createField(DSL.name("route_shape"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geography\""), this, "A PostGIS LinestringZ geography in EPSG:4326 describing the shape of the route.");

    /**
     * The column <code>deleted.route_1637329168554.on_line_id</code>. The line
     * to which this route belongs.
     */
    public final TableField<Record, UUID> ON_LINE_ID = createField(DSL.name("on_line_id"), SQLDataType.UUID, this, "The line to which this route belongs.");

    /**
     * The column <code>deleted.route_1637329168554.validity_start</code>. The
     * point in time when the route becomes valid. If NULL, the route has been
     * always valid.
     */
    public final TableField<Record, OffsetDateTime> VALIDITY_START = createField(DSL.name("validity_start"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "The point in time when the route becomes valid. If NULL, the route has been always valid.");

    /**
     * The column <code>deleted.route_1637329168554.validity_end</code>. The
     * point in time from which onwards the route is no longer valid. If NULL,
     * the route will be always valid.
     */
    public final TableField<Record, OffsetDateTime> VALIDITY_END = createField(DSL.name("validity_end"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "The point in time from which onwards the route is no longer valid. If NULL, the route will be always valid.");

    /**
     * The column <code>deleted.route_1637329168554.priority</code>. The
     * priority of the route definition. The definition may be overridden by
     * higher priority definitions.
     */
    public final TableField<Record, Integer> PRIORITY = createField(DSL.name("priority"), SQLDataType.INTEGER, this, "The priority of the route definition. The definition may be overridden by higher priority definitions.");

    private Route_1637329168554(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Route_1637329168554(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("The routes from Transmodel: https://www.transmodel-cen.eu/model/index.htm?goto=2:1:3:483"), TableOptions.view("create view \"route_1637329168554\" as  SELECT r.route_id,\n    r.description_i18n,\n    r.starts_from_scheduled_stop_point_id,\n    r.ends_at_scheduled_stop_point_id,\n    (st_linemerge(st_collect(\n        CASE\n            WHEN ilar.is_traversal_forwards THEN (il.shape)::geometry\n            ELSE st_reverse((il.shape)::geometry)\n        END)))::geography AS route_shape,\n    r.on_line_id,\n    r.validity_start,\n    r.validity_end,\n    r.priority\n   FROM (internal_route.route r\n     LEFT JOIN (route.infrastructure_link_along_route ilar\n     JOIN infrastructure_network.infrastructure_link il ON ((ilar.infrastructure_link_id = il.infrastructure_link_id))) ON ((r.route_id = ilar.route_id)))\n  GROUP BY r.route_id;"));
    }

    /**
     * Create an aliased <code>deleted.route_1637329168554</code> table
     * reference
     */
    public Route_1637329168554(String alias) {
        this(DSL.name(alias), ROUTE_1637329168554);
    }

    /**
     * Create an aliased <code>deleted.route_1637329168554</code> table
     * reference
     */
    public Route_1637329168554(Name alias) {
        this(alias, ROUTE_1637329168554);
    }

    /**
     * Create a <code>deleted.route_1637329168554</code> table reference
     */
    public Route_1637329168554() {
        this(DSL.name("route_1637329168554"), null);
    }

    public <O extends Record> Route_1637329168554(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, ROUTE_1637329168554);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Deleted.DELETED;
    }

    @Override
    public Route_1637329168554 as(String alias) {
        return new Route_1637329168554(DSL.name(alias), this);
    }

    @Override
    public Route_1637329168554 as(Name alias) {
        return new Route_1637329168554(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Route_1637329168554 rename(String name) {
        return new Route_1637329168554(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Route_1637329168554 rename(Name name) {
        return new Route_1637329168554(name, null);
    }
}
