/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.internal_route.tables;


import fi.hsl.jore.jore4.jooq.internal_route.InternalRoute;
import fi.hsl.jore.jore4.jooq.internal_route.Keys;
import fi.hsl.jore.jore4.jooq.internal_route.tables.records.RouteRecord;
import fi.hsl.jore.jore4.jooq.internal_service_pattern.tables.ScheduledStopPoint;
import fi.hsl.jore.jore4.jooq.route.tables.Direction;
import fi.hsl.jore.jore4.jooq.route.tables.Line;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Route extends TableImpl<RouteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>internal_route.route</code>
     */
    public static final Route ROUTE = new Route();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RouteRecord> getRecordType() {
        return RouteRecord.class;
    }

    /**
     * The column <code>internal_route.route.route_id</code>.
     */
    public final TableField<RouteRecord, UUID> ROUTE_ID = createField(DSL.name("route_id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field("gen_random_uuid()", SQLDataType.UUID)), this, "");

    /**
     * The column <code>internal_route.route.description_i18n</code>.
     */
    public final TableField<RouteRecord, String> DESCRIPTION_I18N = createField(DSL.name("description_i18n"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>internal_route.route.starts_from_scheduled_stop_point_id</code>.
     */
    public final TableField<RouteRecord, UUID> STARTS_FROM_SCHEDULED_STOP_POINT_ID = createField(DSL.name("starts_from_scheduled_stop_point_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>internal_route.route.ends_at_scheduled_stop_point_id</code>.
     */
    public final TableField<RouteRecord, UUID> ENDS_AT_SCHEDULED_STOP_POINT_ID = createField(DSL.name("ends_at_scheduled_stop_point_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>internal_route.route.on_line_id</code>.
     */
    public final TableField<RouteRecord, UUID> ON_LINE_ID = createField(DSL.name("on_line_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>internal_route.route.validity_start</code>.
     */
    public final TableField<RouteRecord, OffsetDateTime> VALIDITY_START = createField(DSL.name("validity_start"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>internal_route.route.validity_end</code>.
     */
    public final TableField<RouteRecord, OffsetDateTime> VALIDITY_END = createField(DSL.name("validity_end"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>internal_route.route.priority</code>.
     */
    public final TableField<RouteRecord, Integer> PRIORITY = createField(DSL.name("priority"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>internal_route.route.label</code>.
     */
    public final TableField<RouteRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>internal_route.route.direction</code>.
     */
    public final TableField<RouteRecord, String> DIRECTION = createField(DSL.name("direction"), SQLDataType.CLOB.nullable(false), this, "");

    private Route(Name alias, Table<RouteRecord> aliased) {
        this(alias, aliased, null);
    }

    private Route(Name alias, Table<RouteRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>internal_route.route</code> table reference
     */
    public Route(String alias) {
        this(DSL.name(alias), ROUTE);
    }

    /**
     * Create an aliased <code>internal_route.route</code> table reference
     */
    public Route(Name alias) {
        this(alias, ROUTE);
    }

    /**
     * Create a <code>internal_route.route</code> table reference
     */
    public Route() {
        this(DSL.name("route"), null);
    }

    public <O extends Record> Route(Table<O> child, ForeignKey<O, RouteRecord> key) {
        super(child, key, ROUTE);
    }

    @Override
    public Schema getSchema() {
        return InternalRoute.INTERNAL_ROUTE;
    }

    @Override
    public UniqueKey<RouteRecord> getPrimaryKey() {
        return Keys.ROUTE_PKEY;
    }

    @Override
    public List<UniqueKey<RouteRecord>> getKeys() {
        return Arrays.<UniqueKey<RouteRecord>>asList(Keys.ROUTE_PKEY);
    }

    @Override
    public List<ForeignKey<RouteRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RouteRecord, ?>>asList(Keys.ROUTE__ROUTE_STARTS_FROM_SCHEDULED_STOP_POINT_ID_FKEY, Keys.ROUTE__ROUTE_ENDS_AT_SCHEDULED_STOP_POINT_ID_FKEY, Keys.ROUTE__ROUTE_ON_LINE_ID_FKEY, Keys.ROUTE__ROUTE_DIRECTION_FKEY);
    }

    private transient ScheduledStopPoint _routeStartsFromScheduledStopPointIdFkey;
    private transient ScheduledStopPoint _routeEndsAtScheduledStopPointIdFkey;
    private transient Line _line;
    private transient Direction _direction;

    public ScheduledStopPoint routeStartsFromScheduledStopPointIdFkey() {
        if (_routeStartsFromScheduledStopPointIdFkey == null)
            _routeStartsFromScheduledStopPointIdFkey = new ScheduledStopPoint(this, Keys.ROUTE__ROUTE_STARTS_FROM_SCHEDULED_STOP_POINT_ID_FKEY);

        return _routeStartsFromScheduledStopPointIdFkey;
    }

    public ScheduledStopPoint routeEndsAtScheduledStopPointIdFkey() {
        if (_routeEndsAtScheduledStopPointIdFkey == null)
            _routeEndsAtScheduledStopPointIdFkey = new ScheduledStopPoint(this, Keys.ROUTE__ROUTE_ENDS_AT_SCHEDULED_STOP_POINT_ID_FKEY);

        return _routeEndsAtScheduledStopPointIdFkey;
    }

    public Line line() {
        if (_line == null)
            _line = new Line(this, Keys.ROUTE__ROUTE_ON_LINE_ID_FKEY);

        return _line;
    }

    public Direction direction() {
        if (_direction == null)
            _direction = new Direction(this, Keys.ROUTE__ROUTE_DIRECTION_FKEY);

        return _direction;
    }

    @Override
    public Route as(String alias) {
        return new Route(DSL.name(alias), this);
    }

    @Override
    public Route as(Name alias) {
        return new Route(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Route rename(String name) {
        return new Route(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Route rename(Name name) {
        return new Route(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<UUID, String, UUID, UUID, UUID, OffsetDateTime, OffsetDateTime, Integer, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
