/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.internal_service_pattern;


import fi.hsl.jore.jore4.jooq.internal_service_pattern.tables.ScheduledStopPoint;


/**
 * Convenience access to all tables in internal_service_pattern.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>internal_service_pattern.scheduled_stop_point</code>.
     */
    public static final ScheduledStopPoint SCHEDULED_STOP_POINT = ScheduledStopPoint.SCHEDULED_STOP_POINT;
}
