TRUNCATE TABLE infrastructure_network.infrastructure_links CASCADE;
TRUNCATE TABLE infrastructure_network.infrastructure_links_history CASCADE;
TRUNCATE TABLE infrastructure_network.infrastructure_nodes CASCADE;
TRUNCATE TABLE infrastructure_network.infrastructure_nodes_history CASCADE;
