/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.importer.jooq.infrastructure_network.tables.records;


import fi.hsl.jore.importer.jooq.infrastructure_network.tables.InfrastructureNetworkTypes;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InfrastructureNetworkTypesRecord extends UpdatableRecordImpl<InfrastructureNetworkTypesRecord> implements Record1<String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>infrastructure_network.infrastructure_network_types.infrastructure_network_type</code>.
     */
    public void setInfrastructureNetworkType(String value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>infrastructure_network.infrastructure_network_types.infrastructure_network_type</code>.
     */
    public String getInfrastructureNetworkType() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return InfrastructureNetworkTypes.INFRASTRUCTURE_NETWORK_TYPES.INFRASTRUCTURE_NETWORK_TYPE;
    }

    @Override
    public String component1() {
        return getInfrastructureNetworkType();
    }

    @Override
    public String value1() {
        return getInfrastructureNetworkType();
    }

    @Override
    public InfrastructureNetworkTypesRecord value1(String value) {
        setInfrastructureNetworkType(value);
        return this;
    }

    @Override
    public InfrastructureNetworkTypesRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InfrastructureNetworkTypesRecord
     */
    public InfrastructureNetworkTypesRecord() {
        super(InfrastructureNetworkTypes.INFRASTRUCTURE_NETWORK_TYPES);
    }

    /**
     * Create a detached, initialised InfrastructureNetworkTypesRecord
     */
    public InfrastructureNetworkTypesRecord(String infrastructureNetworkType) {
        super(InfrastructureNetworkTypes.INFRASTRUCTURE_NETWORK_TYPES);

        setInfrastructureNetworkType(infrastructureNetworkType);
    }
}
