/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.importer.jooq.infrastructure_network;


import fi.hsl.jore.importer.jooq.DefaultCatalog;
import fi.hsl.jore.importer.jooq.infrastructure_network.tables.InfrastructureLinkShapes;
import fi.hsl.jore.importer.jooq.infrastructure_network.tables.InfrastructureLinkShapesHistory;
import fi.hsl.jore.importer.jooq.infrastructure_network.tables.InfrastructureLinkShapesStaging;
import fi.hsl.jore.importer.jooq.infrastructure_network.tables.InfrastructureLinkShapesWithHistory;
import fi.hsl.jore.importer.jooq.infrastructure_network.tables.InfrastructureLinks;
import fi.hsl.jore.importer.jooq.infrastructure_network.tables.InfrastructureLinksHistory;
import fi.hsl.jore.importer.jooq.infrastructure_network.tables.InfrastructureLinksStaging;
import fi.hsl.jore.importer.jooq.infrastructure_network.tables.InfrastructureLinksWithHistory;
import fi.hsl.jore.importer.jooq.infrastructure_network.tables.InfrastructureNetworkTypes;
import fi.hsl.jore.importer.jooq.infrastructure_network.tables.InfrastructureNodeTypes;
import fi.hsl.jore.importer.jooq.infrastructure_network.tables.InfrastructureNodes;
import fi.hsl.jore.importer.jooq.infrastructure_network.tables.InfrastructureNodesHistory;
import fi.hsl.jore.importer.jooq.infrastructure_network.tables.InfrastructureNodesStaging;
import fi.hsl.jore.importer.jooq.infrastructure_network.tables.InfrastructureNodesWithHistory;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InfrastructureNetwork extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>infrastructure_network</code>
     */
    public static final InfrastructureNetwork INFRASTRUCTURE_NETWORK = new InfrastructureNetwork();

    /**
     * The table <code>infrastructure_network.infrastructure_link_shapes</code>.
     */
    public final InfrastructureLinkShapes INFRASTRUCTURE_LINK_SHAPES = InfrastructureLinkShapes.INFRASTRUCTURE_LINK_SHAPES;

    /**
     * The table <code>infrastructure_network.infrastructure_link_shapes_history</code>.
     */
    public final InfrastructureLinkShapesHistory INFRASTRUCTURE_LINK_SHAPES_HISTORY = InfrastructureLinkShapesHistory.INFRASTRUCTURE_LINK_SHAPES_HISTORY;

    /**
     * The table <code>infrastructure_network.infrastructure_link_shapes_staging</code>.
     */
    public final InfrastructureLinkShapesStaging INFRASTRUCTURE_LINK_SHAPES_STAGING = InfrastructureLinkShapesStaging.INFRASTRUCTURE_LINK_SHAPES_STAGING;

    /**
     * The table <code>infrastructure_network.infrastructure_link_shapes_with_history</code>.
     */
    public final InfrastructureLinkShapesWithHistory INFRASTRUCTURE_LINK_SHAPES_WITH_HISTORY = InfrastructureLinkShapesWithHistory.INFRASTRUCTURE_LINK_SHAPES_WITH_HISTORY;

    /**
     * The table <code>infrastructure_network.infrastructure_links</code>.
     */
    public final InfrastructureLinks INFRASTRUCTURE_LINKS = InfrastructureLinks.INFRASTRUCTURE_LINKS;

    /**
     * The table <code>infrastructure_network.infrastructure_links_history</code>.
     */
    public final InfrastructureLinksHistory INFRASTRUCTURE_LINKS_HISTORY = InfrastructureLinksHistory.INFRASTRUCTURE_LINKS_HISTORY;

    /**
     * The table <code>infrastructure_network.infrastructure_links_staging</code>.
     */
    public final InfrastructureLinksStaging INFRASTRUCTURE_LINKS_STAGING = InfrastructureLinksStaging.INFRASTRUCTURE_LINKS_STAGING;

    /**
     * The table <code>infrastructure_network.infrastructure_links_with_history</code>.
     */
    public final InfrastructureLinksWithHistory INFRASTRUCTURE_LINKS_WITH_HISTORY = InfrastructureLinksWithHistory.INFRASTRUCTURE_LINKS_WITH_HISTORY;

    /**
     * The table <code>infrastructure_network.infrastructure_network_types</code>.
     */
    public final InfrastructureNetworkTypes INFRASTRUCTURE_NETWORK_TYPES = InfrastructureNetworkTypes.INFRASTRUCTURE_NETWORK_TYPES;

    /**
     * The table <code>infrastructure_network.infrastructure_node_types</code>.
     */
    public final InfrastructureNodeTypes INFRASTRUCTURE_NODE_TYPES = InfrastructureNodeTypes.INFRASTRUCTURE_NODE_TYPES;

    /**
     * The table <code>infrastructure_network.infrastructure_nodes</code>.
     */
    public final InfrastructureNodes INFRASTRUCTURE_NODES = InfrastructureNodes.INFRASTRUCTURE_NODES;

    /**
     * The table <code>infrastructure_network.infrastructure_nodes_history</code>.
     */
    public final InfrastructureNodesHistory INFRASTRUCTURE_NODES_HISTORY = InfrastructureNodesHistory.INFRASTRUCTURE_NODES_HISTORY;

    /**
     * The table <code>infrastructure_network.infrastructure_nodes_staging</code>.
     */
    public final InfrastructureNodesStaging INFRASTRUCTURE_NODES_STAGING = InfrastructureNodesStaging.INFRASTRUCTURE_NODES_STAGING;

    /**
     * The table <code>infrastructure_network.infrastructure_nodes_with_history</code>.
     */
    public final InfrastructureNodesWithHistory INFRASTRUCTURE_NODES_WITH_HISTORY = InfrastructureNodesWithHistory.INFRASTRUCTURE_NODES_WITH_HISTORY;

    /**
     * No further instances allowed
     */
    private InfrastructureNetwork() {
        super("infrastructure_network", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            InfrastructureLinkShapes.INFRASTRUCTURE_LINK_SHAPES,
            InfrastructureLinkShapesHistory.INFRASTRUCTURE_LINK_SHAPES_HISTORY,
            InfrastructureLinkShapesStaging.INFRASTRUCTURE_LINK_SHAPES_STAGING,
            InfrastructureLinkShapesWithHistory.INFRASTRUCTURE_LINK_SHAPES_WITH_HISTORY,
            InfrastructureLinks.INFRASTRUCTURE_LINKS,
            InfrastructureLinksHistory.INFRASTRUCTURE_LINKS_HISTORY,
            InfrastructureLinksStaging.INFRASTRUCTURE_LINKS_STAGING,
            InfrastructureLinksWithHistory.INFRASTRUCTURE_LINKS_WITH_HISTORY,
            InfrastructureNetworkTypes.INFRASTRUCTURE_NETWORK_TYPES,
            InfrastructureNodeTypes.INFRASTRUCTURE_NODE_TYPES,
            InfrastructureNodes.INFRASTRUCTURE_NODES,
            InfrastructureNodesHistory.INFRASTRUCTURE_NODES_HISTORY,
            InfrastructureNodesStaging.INFRASTRUCTURE_NODES_STAGING,
            InfrastructureNodesWithHistory.INFRASTRUCTURE_NODES_WITH_HISTORY);
    }
}
