/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.importer.jooq.stops.tables;


import fi.hsl.jore.importer.config.jooq.converter.time_range.TimeRange;
import fi.hsl.jore.importer.config.jooq.converter.time_range.TimeRangeBinding;
import fi.hsl.jore.importer.jooq.stops.Stops;
import fi.hsl.jore.importer.jooq.stops.tables.records.StopPlacesHistoryRecord;

import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StopPlacesHistory extends TableImpl<StopPlacesHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stops.stop_places_history</code>
     */
    public static final StopPlacesHistory STOP_PLACES_HISTORY = new StopPlacesHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StopPlacesHistoryRecord> getRecordType() {
        return StopPlacesHistoryRecord.class;
    }

    /**
     * The column <code>stops.stop_places_history.stops_stop_place_id</code>.
     */
    public final TableField<StopPlacesHistoryRecord, UUID> STOPS_STOP_PLACE_ID = createField(DSL.name("stops_stop_place_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column
     * <code>stops.stop_places_history.stops_stop_place_ext_id</code>.
     */
    public final TableField<StopPlacesHistoryRecord, String> STOPS_STOP_PLACE_EXT_ID = createField(DSL.name("stops_stop_place_ext_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>stops.stop_places_history.stops_stop_place_name</code>.
     */
    public final TableField<StopPlacesHistoryRecord, JSONB> STOPS_STOP_PLACE_NAME = createField(DSL.name("stops_stop_place_name"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column
     * <code>stops.stop_places_history.stops_stop_place_long_name</code>.
     */
    public final TableField<StopPlacesHistoryRecord, JSONB> STOPS_STOP_PLACE_LONG_NAME = createField(DSL.name("stops_stop_place_long_name"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column
     * <code>stops.stop_places_history.stops_stop_place_location</code>.
     */
    public final TableField<StopPlacesHistoryRecord, JSONB> STOPS_STOP_PLACE_LOCATION = createField(DSL.name("stops_stop_place_location"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column
     * <code>stops.stop_places_history.stops_stop_place_sys_period</code>.
     */
    public final TableField<StopPlacesHistoryRecord, TimeRange> STOPS_STOP_PLACE_SYS_PERIOD = createField(DSL.name("stops_stop_place_sys_period"), DefaultDataType.getDefaultDataType("\"pg_catalog\".\"tstzrange\"").nullable(false), this, "", new TimeRangeBinding());

    private StopPlacesHistory(Name alias, Table<StopPlacesHistoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private StopPlacesHistory(Name alias, Table<StopPlacesHistoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>stops.stop_places_history</code> table reference
     */
    public StopPlacesHistory(String alias) {
        this(DSL.name(alias), STOP_PLACES_HISTORY);
    }

    /**
     * Create an aliased <code>stops.stop_places_history</code> table reference
     */
    public StopPlacesHistory(Name alias) {
        this(alias, STOP_PLACES_HISTORY);
    }

    /**
     * Create a <code>stops.stop_places_history</code> table reference
     */
    public StopPlacesHistory() {
        this(DSL.name("stop_places_history"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Stops.STOPS;
    }

    @Override
    public StopPlacesHistory as(String alias) {
        return new StopPlacesHistory(DSL.name(alias), this);
    }

    @Override
    public StopPlacesHistory as(Name alias) {
        return new StopPlacesHistory(alias, this);
    }

    @Override
    public StopPlacesHistory as(Table<?> alias) {
        return new StopPlacesHistory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public StopPlacesHistory rename(String name) {
        return new StopPlacesHistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StopPlacesHistory rename(Name name) {
        return new StopPlacesHistory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public StopPlacesHistory rename(Table<?> name) {
        return new StopPlacesHistory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StopPlacesHistory where(Condition condition) {
        return new StopPlacesHistory(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StopPlacesHistory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StopPlacesHistory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StopPlacesHistory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StopPlacesHistory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StopPlacesHistory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StopPlacesHistory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StopPlacesHistory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StopPlacesHistory whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StopPlacesHistory whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
