/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.route;


import fi.hsl.jore.jore4.jooq.route.routines.RouteShape;

import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Record;


/**
 * Convenience access to all stored procedures and functions in route.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public static Object routeShape(
          Configuration configuration
        , Record routeRow
    ) {
        RouteShape f = new RouteShape();
        f.setRouteRow(routeRow);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public static Field<Object> routeShape(
          Record routeRow
    ) {
        RouteShape f = new RouteShape();
        f.setRouteRow(routeRow);

        return f.asField();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public static Field<Object> routeShape(
          Field<Record> routeRow
    ) {
        RouteShape f = new RouteShape();
        f.setRouteRow(routeRow);

        return f.asField();
    }
}
