/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.importer.jooq.network.tables.records;


import fi.hsl.jore.importer.config.jooq.converter.date_range.DateRange;
import fi.hsl.jore.importer.config.jooq.converter.time_range.TimeRange;
import fi.hsl.jore.importer.jooq.network.tables.NetworkLineHeaders;

import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NetworkLineHeadersRecord extends UpdatableRecordImpl<NetworkLineHeadersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>network.network_line_headers.network_line_header_id</code>.
     */
    public void setNetworkLineHeaderId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>network.network_line_headers.network_line_header_id</code>.
     */
    public UUID getNetworkLineHeaderId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>network.network_line_headers.network_line_id</code>.
     */
    public void setNetworkLineId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>network.network_line_headers.network_line_id</code>.
     */
    public UUID getNetworkLineId() {
        return (UUID) get(1);
    }

    /**
     * Setter for
     * <code>network.network_line_headers.network_line_header_ext_id</code>.
     */
    public void setNetworkLineHeaderExtId(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>network.network_line_headers.network_line_header_ext_id</code>.
     */
    public String getNetworkLineHeaderExtId() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>network.network_line_headers.network_line_header_name</code>.
     */
    public void setNetworkLineHeaderName(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>network.network_line_headers.network_line_header_name</code>.
     */
    public JSONB getNetworkLineHeaderName() {
        return (JSONB) get(3);
    }

    /**
     * Setter for
     * <code>network.network_line_headers.network_line_header_name_short</code>.
     */
    public void setNetworkLineHeaderNameShort(JSONB value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>network.network_line_headers.network_line_header_name_short</code>.
     */
    public JSONB getNetworkLineHeaderNameShort() {
        return (JSONB) get(4);
    }

    /**
     * Setter for
     * <code>network.network_line_headers.network_line_header_origin_1</code>.
     */
    public void setNetworkLineHeaderOrigin_1(JSONB value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>network.network_line_headers.network_line_header_origin_1</code>.
     */
    public JSONB getNetworkLineHeaderOrigin_1() {
        return (JSONB) get(5);
    }

    /**
     * Setter for
     * <code>network.network_line_headers.network_line_header_origin_2</code>.
     */
    public void setNetworkLineHeaderOrigin_2(JSONB value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>network.network_line_headers.network_line_header_origin_2</code>.
     */
    public JSONB getNetworkLineHeaderOrigin_2() {
        return (JSONB) get(6);
    }

    /**
     * Setter for
     * <code>network.network_line_headers.network_line_header_valid_date_range</code>.
     */
    public void setNetworkLineHeaderValidDateRange(DateRange value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>network.network_line_headers.network_line_header_valid_date_range</code>.
     */
    public DateRange getNetworkLineHeaderValidDateRange() {
        return (DateRange) get(7);
    }

    /**
     * Setter for
     * <code>network.network_line_headers.network_line_header_sys_period</code>.
     */
    public void setNetworkLineHeaderSysPeriod(TimeRange value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>network.network_line_headers.network_line_header_sys_period</code>.
     */
    public TimeRange getNetworkLineHeaderSysPeriod() {
        return (TimeRange) get(8);
    }

    /**
     * Setter for <code>network.network_line_headers.jore4_line_id</code>.
     */
    public void setJore4LineId(UUID value) {
        set(9, value);
    }

    /**
     * Getter for <code>network.network_line_headers.jore4_line_id</code>.
     */
    public UUID getJore4LineId() {
        return (UUID) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NetworkLineHeadersRecord
     */
    public NetworkLineHeadersRecord() {
        super(NetworkLineHeaders.NETWORK_LINE_HEADERS);
    }

    /**
     * Create a detached, initialised NetworkLineHeadersRecord
     */
    public NetworkLineHeadersRecord(UUID networkLineHeaderId, UUID networkLineId, String networkLineHeaderExtId, JSONB networkLineHeaderName, JSONB networkLineHeaderNameShort, JSONB networkLineHeaderOrigin_1, JSONB networkLineHeaderOrigin_2, DateRange networkLineHeaderValidDateRange, TimeRange networkLineHeaderSysPeriod, UUID jore4LineId) {
        super(NetworkLineHeaders.NETWORK_LINE_HEADERS);

        setNetworkLineHeaderId(networkLineHeaderId);
        setNetworkLineId(networkLineId);
        setNetworkLineHeaderExtId(networkLineHeaderExtId);
        setNetworkLineHeaderName(networkLineHeaderName);
        setNetworkLineHeaderNameShort(networkLineHeaderNameShort);
        setNetworkLineHeaderOrigin_1(networkLineHeaderOrigin_1);
        setNetworkLineHeaderOrigin_2(networkLineHeaderOrigin_2);
        setNetworkLineHeaderValidDateRange(networkLineHeaderValidDateRange);
        setNetworkLineHeaderSysPeriod(networkLineHeaderSysPeriod);
        setJore4LineId(jore4LineId);
        resetChangedOnNotNull();
    }
}
