/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.importer.jooq.network.tables.records;


import fi.hsl.jore.importer.config.jooq.converter.date_range.DateRange;
import fi.hsl.jore.importer.config.jooq.converter.time_range.TimeRange;
import fi.hsl.jore.importer.jooq.network.tables.NetworkLineHeadersWithHistory;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NetworkLineHeadersWithHistoryRecord extends TableRecordImpl<NetworkLineHeadersWithHistoryRecord> implements Record10<UUID, UUID, String, JSONB, JSONB, JSONB, JSONB, DateRange, TimeRange, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>network.network_line_headers_with_history.network_line_header_id</code>.
     */
    public void setNetworkLineHeaderId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>network.network_line_headers_with_history.network_line_header_id</code>.
     */
    public UUID getNetworkLineHeaderId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>network.network_line_headers_with_history.network_line_id</code>.
     */
    public void setNetworkLineId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>network.network_line_headers_with_history.network_line_id</code>.
     */
    public UUID getNetworkLineId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>network.network_line_headers_with_history.network_line_header_ext_id</code>.
     */
    public void setNetworkLineHeaderExtId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>network.network_line_headers_with_history.network_line_header_ext_id</code>.
     */
    public String getNetworkLineHeaderExtId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>network.network_line_headers_with_history.network_line_header_name</code>.
     */
    public void setNetworkLineHeaderName(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>network.network_line_headers_with_history.network_line_header_name</code>.
     */
    public JSONB getNetworkLineHeaderName() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>network.network_line_headers_with_history.network_line_header_name_short</code>.
     */
    public void setNetworkLineHeaderNameShort(JSONB value) {
        set(4, value);
    }

    /**
     * Getter for <code>network.network_line_headers_with_history.network_line_header_name_short</code>.
     */
    public JSONB getNetworkLineHeaderNameShort() {
        return (JSONB) get(4);
    }

    /**
     * Setter for <code>network.network_line_headers_with_history.network_line_header_origin_1</code>.
     */
    public void setNetworkLineHeaderOrigin_1(JSONB value) {
        set(5, value);
    }

    /**
     * Getter for <code>network.network_line_headers_with_history.network_line_header_origin_1</code>.
     */
    public JSONB getNetworkLineHeaderOrigin_1() {
        return (JSONB) get(5);
    }

    /**
     * Setter for <code>network.network_line_headers_with_history.network_line_header_origin_2</code>.
     */
    public void setNetworkLineHeaderOrigin_2(JSONB value) {
        set(6, value);
    }

    /**
     * Getter for <code>network.network_line_headers_with_history.network_line_header_origin_2</code>.
     */
    public JSONB getNetworkLineHeaderOrigin_2() {
        return (JSONB) get(6);
    }

    /**
     * Setter for <code>network.network_line_headers_with_history.network_line_header_valid_date_range</code>.
     */
    public void setNetworkLineHeaderValidDateRange(DateRange value) {
        set(7, value);
    }

    /**
     * Getter for <code>network.network_line_headers_with_history.network_line_header_valid_date_range</code>.
     */
    public DateRange getNetworkLineHeaderValidDateRange() {
        return (DateRange) get(7);
    }

    /**
     * Setter for <code>network.network_line_headers_with_history.network_line_header_sys_period</code>.
     */
    public void setNetworkLineHeaderSysPeriod(TimeRange value) {
        set(8, value);
    }

    /**
     * Getter for <code>network.network_line_headers_with_history.network_line_header_sys_period</code>.
     */
    public TimeRange getNetworkLineHeaderSysPeriod() {
        return (TimeRange) get(8);
    }

    /**
     * Setter for <code>network.network_line_headers_with_history.jore4_line_id</code>.
     */
    public void setJore4LineId(UUID value) {
        set(9, value);
    }

    /**
     * Getter for <code>network.network_line_headers_with_history.jore4_line_id</code>.
     */
    public UUID getJore4LineId() {
        return (UUID) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<UUID, UUID, String, JSONB, JSONB, JSONB, JSONB, DateRange, TimeRange, UUID> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<UUID, UUID, String, JSONB, JSONB, JSONB, JSONB, DateRange, TimeRange, UUID> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return NetworkLineHeadersWithHistory.NETWORK_LINE_HEADERS_WITH_HISTORY.NETWORK_LINE_HEADER_ID;
    }

    @Override
    public Field<UUID> field2() {
        return NetworkLineHeadersWithHistory.NETWORK_LINE_HEADERS_WITH_HISTORY.NETWORK_LINE_ID;
    }

    @Override
    public Field<String> field3() {
        return NetworkLineHeadersWithHistory.NETWORK_LINE_HEADERS_WITH_HISTORY.NETWORK_LINE_HEADER_EXT_ID;
    }

    @Override
    public Field<JSONB> field4() {
        return NetworkLineHeadersWithHistory.NETWORK_LINE_HEADERS_WITH_HISTORY.NETWORK_LINE_HEADER_NAME;
    }

    @Override
    public Field<JSONB> field5() {
        return NetworkLineHeadersWithHistory.NETWORK_LINE_HEADERS_WITH_HISTORY.NETWORK_LINE_HEADER_NAME_SHORT;
    }

    @Override
    public Field<JSONB> field6() {
        return NetworkLineHeadersWithHistory.NETWORK_LINE_HEADERS_WITH_HISTORY.NETWORK_LINE_HEADER_ORIGIN_1;
    }

    @Override
    public Field<JSONB> field7() {
        return NetworkLineHeadersWithHistory.NETWORK_LINE_HEADERS_WITH_HISTORY.NETWORK_LINE_HEADER_ORIGIN_2;
    }

    @Override
    public Field<DateRange> field8() {
        return NetworkLineHeadersWithHistory.NETWORK_LINE_HEADERS_WITH_HISTORY.NETWORK_LINE_HEADER_VALID_DATE_RANGE;
    }

    @Override
    public Field<TimeRange> field9() {
        return NetworkLineHeadersWithHistory.NETWORK_LINE_HEADERS_WITH_HISTORY.NETWORK_LINE_HEADER_SYS_PERIOD;
    }

    @Override
    public Field<UUID> field10() {
        return NetworkLineHeadersWithHistory.NETWORK_LINE_HEADERS_WITH_HISTORY.JORE4_LINE_ID;
    }

    @Override
    public UUID component1() {
        return getNetworkLineHeaderId();
    }

    @Override
    public UUID component2() {
        return getNetworkLineId();
    }

    @Override
    public String component3() {
        return getNetworkLineHeaderExtId();
    }

    @Override
    public JSONB component4() {
        return getNetworkLineHeaderName();
    }

    @Override
    public JSONB component5() {
        return getNetworkLineHeaderNameShort();
    }

    @Override
    public JSONB component6() {
        return getNetworkLineHeaderOrigin_1();
    }

    @Override
    public JSONB component7() {
        return getNetworkLineHeaderOrigin_2();
    }

    @Override
    public DateRange component8() {
        return getNetworkLineHeaderValidDateRange();
    }

    @Override
    public TimeRange component9() {
        return getNetworkLineHeaderSysPeriod();
    }

    @Override
    public UUID component10() {
        return getJore4LineId();
    }

    @Override
    public UUID value1() {
        return getNetworkLineHeaderId();
    }

    @Override
    public UUID value2() {
        return getNetworkLineId();
    }

    @Override
    public String value3() {
        return getNetworkLineHeaderExtId();
    }

    @Override
    public JSONB value4() {
        return getNetworkLineHeaderName();
    }

    @Override
    public JSONB value5() {
        return getNetworkLineHeaderNameShort();
    }

    @Override
    public JSONB value6() {
        return getNetworkLineHeaderOrigin_1();
    }

    @Override
    public JSONB value7() {
        return getNetworkLineHeaderOrigin_2();
    }

    @Override
    public DateRange value8() {
        return getNetworkLineHeaderValidDateRange();
    }

    @Override
    public TimeRange value9() {
        return getNetworkLineHeaderSysPeriod();
    }

    @Override
    public UUID value10() {
        return getJore4LineId();
    }

    @Override
    public NetworkLineHeadersWithHistoryRecord value1(UUID value) {
        setNetworkLineHeaderId(value);
        return this;
    }

    @Override
    public NetworkLineHeadersWithHistoryRecord value2(UUID value) {
        setNetworkLineId(value);
        return this;
    }

    @Override
    public NetworkLineHeadersWithHistoryRecord value3(String value) {
        setNetworkLineHeaderExtId(value);
        return this;
    }

    @Override
    public NetworkLineHeadersWithHistoryRecord value4(JSONB value) {
        setNetworkLineHeaderName(value);
        return this;
    }

    @Override
    public NetworkLineHeadersWithHistoryRecord value5(JSONB value) {
        setNetworkLineHeaderNameShort(value);
        return this;
    }

    @Override
    public NetworkLineHeadersWithHistoryRecord value6(JSONB value) {
        setNetworkLineHeaderOrigin_1(value);
        return this;
    }

    @Override
    public NetworkLineHeadersWithHistoryRecord value7(JSONB value) {
        setNetworkLineHeaderOrigin_2(value);
        return this;
    }

    @Override
    public NetworkLineHeadersWithHistoryRecord value8(DateRange value) {
        setNetworkLineHeaderValidDateRange(value);
        return this;
    }

    @Override
    public NetworkLineHeadersWithHistoryRecord value9(TimeRange value) {
        setNetworkLineHeaderSysPeriod(value);
        return this;
    }

    @Override
    public NetworkLineHeadersWithHistoryRecord value10(UUID value) {
        setJore4LineId(value);
        return this;
    }

    @Override
    public NetworkLineHeadersWithHistoryRecord values(UUID value1, UUID value2, String value3, JSONB value4, JSONB value5, JSONB value6, JSONB value7, DateRange value8, TimeRange value9, UUID value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NetworkLineHeadersWithHistoryRecord
     */
    public NetworkLineHeadersWithHistoryRecord() {
        super(NetworkLineHeadersWithHistory.NETWORK_LINE_HEADERS_WITH_HISTORY);
    }

    /**
     * Create a detached, initialised NetworkLineHeadersWithHistoryRecord
     */
    public NetworkLineHeadersWithHistoryRecord(UUID networkLineHeaderId, UUID networkLineId, String networkLineHeaderExtId, JSONB networkLineHeaderName, JSONB networkLineHeaderNameShort, JSONB networkLineHeaderOrigin_1, JSONB networkLineHeaderOrigin_2, DateRange networkLineHeaderValidDateRange, TimeRange networkLineHeaderSysPeriod, UUID jore4LineId) {
        super(NetworkLineHeadersWithHistory.NETWORK_LINE_HEADERS_WITH_HISTORY);

        setNetworkLineHeaderId(networkLineHeaderId);
        setNetworkLineId(networkLineId);
        setNetworkLineHeaderExtId(networkLineHeaderExtId);
        setNetworkLineHeaderName(networkLineHeaderName);
        setNetworkLineHeaderNameShort(networkLineHeaderNameShort);
        setNetworkLineHeaderOrigin_1(networkLineHeaderOrigin_1);
        setNetworkLineHeaderOrigin_2(networkLineHeaderOrigin_2);
        setNetworkLineHeaderValidDateRange(networkLineHeaderValidDateRange);
        setNetworkLineHeaderSysPeriod(networkLineHeaderSysPeriod);
        setJore4LineId(jore4LineId);
    }
}
