version: '2'

services:

  importer-jooq-database:
    image: postgis/postgis:12-3.1-alpine
    container_name: importer-database
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devdb
      - POSTGRES_PASSWORD=devdb
    ports:
      - "16000:5432"
