---
version: "3.8"
services:
  jore4-hasura:
    container_name: "hasura"
    image: "hsldevcom/jore4-hasura:main--7d60ba6bf9115c59dff4421f8a8ea132561a0ab3"
    restart: "unless-stopped"
    networks:
      - jore4
    environment:
      HASURA_GRAPHQL_AUTH_HOOK: "http://jore4-auth:8080/public/v1/hasura/webhook"
      HASURA_GRAPHQL_AUTH_HOOK_MODE: "GET"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_METADATA_DIR: "/hasura-metadata"
      HASURA_GRAPHQL_MIGRATIONS_DIR: "/hasura-migrations"
      HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT: "60"
      SECRET_STORE_BASE_PATH: "/mnt/secrets-store"
    ports:
      - "127.0.0.1:3201:8080"
    secrets:
      - source: hasura-db-auth-username
        target: /mnt/secrets-store/db-auth-username
      - source: hasura-db-hostname
        target: /mnt/secrets-store/db-hostname
      - source: hasura-db-jore3importer-username
        target: /mnt/secrets-store/db-jore3importer-username
      - source: hasura-db-name
        target: /mnt/secrets-store/db-name
      - source: hasura-db-password
        target: /mnt/secrets-store/db-password
      - source: hasura-db-username
        target: /mnt/secrets-store/db-username
      - source: hasura-hasura-admin-secret
        target: /mnt/secrets-store/hasura-admin-secret
    extra_hosts:
      - "host.docker.internal:host-gateway"
  importer:
    container_name: importer
    build:
      context: ../
      dockerfile: ./Dockerfile
    restart: "unless-stopped"
    environment:
      - SOURCE_DB_HOSTNAME=mssqltestdb
      - SOURCE_DB_PORT=1433
      - SOURCE_DB_DATABASE=jore3testdb
      - SOURCE_DB_USERNAME=sa
      - SOURCE_DB_PASSWORD=P@ssw0rd
      - IMPORTER_DB_URL=jdbc:postgresql://importer-jooq-database:5432/devdb?stringtype=unspecified
      - IMPORTER_DB_USERNAME=devdb
      - IMPORTER_DB_PASSWORD=devdb
      - JORE_IMPORTER_MIGRATE=true
    networks:
      - jore4
    ports:
      - "127.0.0.1:3200:8080"

  importer-jooq-database:
    image: postgis/postgis:12-3.1-alpine
    container_name: importer-database
    restart: "unless-stopped"
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devdb
      - POSTGRES_PASSWORD=devdb
    ports:
      - "127.0.0.1:16000:5432"
    networks:
      - jore4

  importer-test-database:
    image: postgis/postgis:12-3.1-alpine
    container_name: importer-test-database
    environment:
      - POSTGRES_DB=importertestdatabase
      - POSTGRES_USER=importertestdatabase
      - POSTGRES_PASSWORD=importertestdatabase
    ports:
      - "127.0.0.1:17000:5432"
    networks:
      - jore4

  jore4-mssqltestdb:
    container_name: "mssqltestdb"
    image: "hsldevcom/jore4-mssql-testdb:schema-only-main--a650cec4970a6c78335e50a24223e7baa0916dc4"
    restart: "unless-stopped"
    networks:
      - jore4
    environment:
      SA_PASSWORD: "P@ssw0rd"
    ports:
      - "127.0.0.1:1433:1433"
networks:
    jore4:

