version: '2'

services:

  importer-test-database:
    image: postgis/postgis:12-3.1-alpine
    container_name: importer-test-database
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=testdb
      - POSTGRES_PASSWORD=testdb
    ports:
      - "17000:5432"
