/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.importer.jooq.network.tables;


import fi.hsl.jore.importer.config.jooq.converter.time_range.TimeRange;
import fi.hsl.jore.importer.config.jooq.converter.time_range.TimeRangeBinding;
import fi.hsl.jore.importer.jooq.network.Network;
import fi.hsl.jore.importer.jooq.network.tables.records.NetworkRoutePointsWithHistoryRecord;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NetworkRoutePointsWithHistory extends TableImpl<NetworkRoutePointsWithHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>network.network_route_points_with_history</code>
     */
    public static final NetworkRoutePointsWithHistory NETWORK_ROUTE_POINTS_WITH_HISTORY = new NetworkRoutePointsWithHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NetworkRoutePointsWithHistoryRecord> getRecordType() {
        return NetworkRoutePointsWithHistoryRecord.class;
    }

    /**
     * The column
     * <code>network.network_route_points_with_history.network_route_point_id</code>.
     */
    public final TableField<NetworkRoutePointsWithHistoryRecord, UUID> NETWORK_ROUTE_POINT_ID = createField(DSL.name("network_route_point_id"), SQLDataType.UUID, this, "");

    /**
     * The column
     * <code>network.network_route_points_with_history.network_route_direction_id</code>.
     */
    public final TableField<NetworkRoutePointsWithHistoryRecord, UUID> NETWORK_ROUTE_DIRECTION_ID = createField(DSL.name("network_route_direction_id"), SQLDataType.UUID, this, "");

    /**
     * The column
     * <code>network.network_route_points_with_history.infrastructure_node</code>.
     */
    public final TableField<NetworkRoutePointsWithHistoryRecord, UUID> INFRASTRUCTURE_NODE = createField(DSL.name("infrastructure_node"), SQLDataType.UUID, this, "");

    /**
     * The column
     * <code>network.network_route_points_with_history.network_route_point_ext_id</code>.
     */
    public final TableField<NetworkRoutePointsWithHistoryRecord, String> NETWORK_ROUTE_POINT_EXT_ID = createField(DSL.name("network_route_point_ext_id"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>network.network_route_points_with_history.network_route_point_order</code>.
     */
    public final TableField<NetworkRoutePointsWithHistoryRecord, Integer> NETWORK_ROUTE_POINT_ORDER = createField(DSL.name("network_route_point_order"), SQLDataType.INTEGER, this, "");

    /**
     * The column
     * <code>network.network_route_points_with_history.network_route_point_sys_period</code>.
     */
    public final TableField<NetworkRoutePointsWithHistoryRecord, TimeRange> NETWORK_ROUTE_POINT_SYS_PERIOD = createField(DSL.name("network_route_point_sys_period"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"pg_catalog\".\"tstzrange\""), this, "", new TimeRangeBinding());

    private NetworkRoutePointsWithHistory(Name alias, Table<NetworkRoutePointsWithHistoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private NetworkRoutePointsWithHistory(Name alias, Table<NetworkRoutePointsWithHistoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("create view \"network_route_points_with_history\" as  SELECT network_route_points.network_route_point_id,\n    network_route_points.network_route_direction_id,\n    network_route_points.infrastructure_node,\n    network_route_points.network_route_point_ext_id,\n    network_route_points.network_route_point_order,\n    network_route_points.network_route_point_sys_period\n   FROM network.network_route_points\nUNION ALL\n SELECT network_route_points_history.network_route_point_id,\n    network_route_points_history.network_route_direction_id,\n    network_route_points_history.infrastructure_node,\n    network_route_points_history.network_route_point_ext_id,\n    network_route_points_history.network_route_point_order,\n    network_route_points_history.network_route_point_sys_period\n   FROM network.network_route_points_history;"));
    }

    /**
     * Create an aliased <code>network.network_route_points_with_history</code>
     * table reference
     */
    public NetworkRoutePointsWithHistory(String alias) {
        this(DSL.name(alias), NETWORK_ROUTE_POINTS_WITH_HISTORY);
    }

    /**
     * Create an aliased <code>network.network_route_points_with_history</code>
     * table reference
     */
    public NetworkRoutePointsWithHistory(Name alias) {
        this(alias, NETWORK_ROUTE_POINTS_WITH_HISTORY);
    }

    /**
     * Create a <code>network.network_route_points_with_history</code> table
     * reference
     */
    public NetworkRoutePointsWithHistory() {
        this(DSL.name("network_route_points_with_history"), null);
    }

    public <O extends Record> NetworkRoutePointsWithHistory(Table<O> child, ForeignKey<O, NetworkRoutePointsWithHistoryRecord> key) {
        super(child, key, NETWORK_ROUTE_POINTS_WITH_HISTORY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Network.NETWORK;
    }

    @Override
    public NetworkRoutePointsWithHistory as(String alias) {
        return new NetworkRoutePointsWithHistory(DSL.name(alias), this);
    }

    @Override
    public NetworkRoutePointsWithHistory as(Name alias) {
        return new NetworkRoutePointsWithHistory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public NetworkRoutePointsWithHistory rename(String name) {
        return new NetworkRoutePointsWithHistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NetworkRoutePointsWithHistory rename(Name name) {
        return new NetworkRoutePointsWithHistory(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, UUID, UUID, String, Integer, TimeRange> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
