/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.journey_pattern.routines;


import fi.hsl.jore.jore4.jooq.journey_pattern.JourneyPattern;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InfraLinkStopRefsAlreadyVerified extends AbstractRoutine<Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter
     * <code>journey_pattern.infra_link_stop_refs_already_verified.RETURN_VALUE</code>.
     */
    public static final Parameter<Boolean> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.BOOLEAN, false, false);

    /**
     * Create a new routine call instance
     */
    public InfraLinkStopRefsAlreadyVerified() {
        super("infra_link_stop_refs_already_verified", JourneyPattern.JOURNEY_PATTERN, SQLDataType.BOOLEAN);

        setReturnParameter(RETURN_VALUE);
    }
}
