/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.network.tables;


import fi.hsl.jore.jore4.jooq.network.Network;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * Transport target, can be used e.g. for cost sharing.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TransportTarget extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>network.transport_target</code>
     */
    public static final TransportTarget TRANSPORT_TARGET = new TransportTarget();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>network.transport_target.transport_target</code>.
     */
    public final TableField<Record, String> TRANSPORT_TARGET_ = createField(DSL.name("transport_target"), SQLDataType.CLOB.nullable(false), this, "");

    private TransportTarget(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TransportTarget(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Transport target, can be used e.g. for cost sharing."), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>network.transport_target</code> table reference
     */
    public TransportTarget(String alias) {
        this(DSL.name(alias), TRANSPORT_TARGET);
    }

    /**
     * Create an aliased <code>network.transport_target</code> table reference
     */
    public TransportTarget(Name alias) {
        this(alias, TRANSPORT_TARGET);
    }

    /**
     * Create a <code>network.transport_target</code> table reference
     */
    public TransportTarget() {
        this(DSL.name("transport_target"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Network.NETWORK;
    }

    @Override
    public TransportTarget as(String alias) {
        return new TransportTarget(DSL.name(alias), this);
    }

    @Override
    public TransportTarget as(Name alias) {
        return new TransportTarget(alias, this);
    }

    @Override
    public TransportTarget as(Table<?> alias) {
        return new TransportTarget(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TransportTarget rename(String name) {
        return new TransportTarget(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TransportTarget rename(Name name) {
        return new TransportTarget(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TransportTarget rename(Table<?> name) {
        return new TransportTarget(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransportTarget where(Condition condition) {
        return new TransportTarget(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransportTarget where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransportTarget where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransportTarget where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TransportTarget where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TransportTarget where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TransportTarget where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TransportTarget where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransportTarget whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransportTarget whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
