@startuml

control importNodesFlow as flow
control prepareNodesStep as prepare_step
control importNodesStep as import_step
control commitNodesStep as commit_step
participant NodeReader as reader
database SourceDb as sdb
participant NodeProcessor as processor
participant GenericImportWriter as writer
database StagingTable as staging_table
database TargetTable as target_table

flow -> prepare_step
activate prepare_step

prepare_step -> staging_table : //truncate//
deactivate prepare_step

flow -> import_step
activate import_step

group Read all rows in chunks

    group Read and process chunk of N elements

        import_step -> reader : //read()//
        activate reader

        reader -> sdb : ""import_nodes.sql""
        reader <- sdb : ""ResultSet""

        import_step <- reader :""JrNode"" | "null"
        deactivate reader

        import_step -> processor : //process(//""JrNode""//)//
        activate processor
        import_step <-- processor : ""PersistableNode""
        deactivate processor

    end

    import_step -> writer : //write(//""Chunk<PersistableNode>""//)//
    activate writer
    writer -> staging_table : JDBC batch insert
    import_step <-- writer
    deactivate writer

end

deactivate import_step

flow -> commit_step
activate commit_step

commit_step -> staging_table : //commit//
staging_table -> target_table : //insert/update/delete//
commit_step <- target_table : inserted/updated/deleted ""NodePK""s

commit_step -> staging_table : //truncate//
deactivate commit_step

@enduml
