@startuml
'https://plantuml.com/activity-diagram-beta

start

partition importNodesFlow {
    :prepareNodesStep;
    :importNodesStep;
    :commitNodesStep;
}

partition importLinksFlow {
    :prepareLinksStep;
    :importLinksStep;
    :commitLinksStep;
}

partition importLinkPointsFlow {
    :prepareLinkPointsStep;
    :importLinkPointsStep;
    :commitLinkPointsStep;
}

partition importLinesFlow {
    :prepareLinesStep;
    :importLinesStep;
    :commitLinesStep;
}

stop

@enduml
