@startuml

control importLinksFlow as flow
control prepareLinksStep as prepare_step
control importLinksStep as import_step
control commitLinksStep as commit_step
participant LinkRowReader as reader
database SourceDb as sdb
participant LinkRowProcessor as processor
participant GenericImportWriter as writer
database StagingTable as staging_table
database TargetTable as target_table

flow -> prepare_step
activate prepare_step

prepare_step -> staging_table : //truncate//
deactivate prepare_step

flow -> import_step
activate import_step

group Read all rows in chunks

    group Read and process chunk of N elements

        import_step -> reader : //read()//
        activate reader

        reader -> sdb : ""import_links.sql""
        reader <- sdb : ""ResultSet""

        import_step <- reader :""LinkRow"" | "null"
        deactivate reader

        import_step -> processor : //process(//""LinkRow""//)//
        activate processor
        import_step <-- processor : ""PersistableLink""
        deactivate processor

    end

    import_step -> writer : //write(//""Chunk<PersistableLink>""//)//
    activate writer
    writer -> staging_table : JDBC batch insert
    import_step <-- writer
    deactivate writer

end

deactivate import_step

flow -> commit_step
activate commit_step

commit_step -> staging_table : //commit//
staging_table -> target_table : //insert/update/delete//
commit_step <- target_table : inserted/updated/deleted ""LinkPK""s

commit_step -> staging_table : //truncate//
deactivate commit_step

@enduml
