/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.route.tables.records;


import fi.hsl.jore.jore4.jooq.route.tables.Line;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * The line from Transmodel: http://www.transmodel-cen.eu/model/index.htm?goto=2:1:3:487
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LineRecord extends UpdatableRecordImpl<LineRecord> implements Record9<UUID, String, String, String, String, OffsetDateTime, OffsetDateTime, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>route.line.line_id</code>. The ID of the line.
     */
    public void setLineId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>route.line.line_id</code>. The ID of the line.
     */
    public UUID getLineId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>route.line.name_i18n</code>. The name of the line. Placeholder for multilingual strings.
     */
    public void setNameI18n(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>route.line.name_i18n</code>. The name of the line. Placeholder for multilingual strings.
     */
    public String getNameI18n() {
        return (String) get(1);
    }

    /**
     * Setter for <code>route.line.short_name_i18n</code>. The shorted name of the line. Placeholder for multilingual strings.
     */
    public void setShortNameI18n(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>route.line.short_name_i18n</code>. The shorted name of the line. Placeholder for multilingual strings.
     */
    public String getShortNameI18n() {
        return (String) get(2);
    }

    /**
     * Setter for <code>route.line.description_i18n</code>. The description of the line. Placeholder for multilingual strings.
     */
    public void setDescriptionI18n(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>route.line.description_i18n</code>. The description of the line. Placeholder for multilingual strings.
     */
    public String getDescriptionI18n() {
        return (String) get(3);
    }

    /**
     * Setter for <code>route.line.primary_vehicle_mode</code>. The mode of the vehicles used as primary on the line.
     */
    public void setPrimaryVehicleMode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>route.line.primary_vehicle_mode</code>. The mode of the vehicles used as primary on the line.
     */
    public String getPrimaryVehicleMode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>route.line.validity_start</code>. The point in time when the line becomes valid. If NULL, the line has been always valid.
     */
    public void setValidityStart(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>route.line.validity_start</code>. The point in time when the line becomes valid. If NULL, the line has been always valid.
     */
    public OffsetDateTime getValidityStart() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>route.line.validity_end</code>. The point in time from which onwards the line is no longer valid. If NULL, the line will be always valid.
     */
    public void setValidityEnd(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>route.line.validity_end</code>. The point in time from which onwards the line is no longer valid. If NULL, the line will be always valid.
     */
    public OffsetDateTime getValidityEnd() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>route.line.priority</code>. The priority of the line definition. The definition may be overridden by higher priority definitions.
     */
    public void setPriority(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>route.line.priority</code>. The priority of the line definition. The definition may be overridden by higher priority definitions.
     */
    public Integer getPriority() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>route.line.label</code>. The label of the line definition. The label is unique for a certain priority and validity period.
     */
    public void setLabel(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>route.line.label</code>. The label of the line definition. The label is unique for a certain priority and validity period.
     */
    public String getLabel() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<UUID, String, String, String, String, OffsetDateTime, OffsetDateTime, Integer, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<UUID, String, String, String, String, OffsetDateTime, OffsetDateTime, Integer, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Line.LINE.LINE_ID;
    }

    @Override
    public Field<String> field2() {
        return Line.LINE.NAME_I18N;
    }

    @Override
    public Field<String> field3() {
        return Line.LINE.SHORT_NAME_I18N;
    }

    @Override
    public Field<String> field4() {
        return Line.LINE.DESCRIPTION_I18N;
    }

    @Override
    public Field<String> field5() {
        return Line.LINE.PRIMARY_VEHICLE_MODE;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return Line.LINE.VALIDITY_START;
    }

    @Override
    public Field<OffsetDateTime> field7() {
        return Line.LINE.VALIDITY_END;
    }

    @Override
    public Field<Integer> field8() {
        return Line.LINE.PRIORITY;
    }

    @Override
    public Field<String> field9() {
        return Line.LINE.LABEL;
    }

    @Override
    public UUID component1() {
        return getLineId();
    }

    @Override
    public String component2() {
        return getNameI18n();
    }

    @Override
    public String component3() {
        return getShortNameI18n();
    }

    @Override
    public String component4() {
        return getDescriptionI18n();
    }

    @Override
    public String component5() {
        return getPrimaryVehicleMode();
    }

    @Override
    public OffsetDateTime component6() {
        return getValidityStart();
    }

    @Override
    public OffsetDateTime component7() {
        return getValidityEnd();
    }

    @Override
    public Integer component8() {
        return getPriority();
    }

    @Override
    public String component9() {
        return getLabel();
    }

    @Override
    public UUID value1() {
        return getLineId();
    }

    @Override
    public String value2() {
        return getNameI18n();
    }

    @Override
    public String value3() {
        return getShortNameI18n();
    }

    @Override
    public String value4() {
        return getDescriptionI18n();
    }

    @Override
    public String value5() {
        return getPrimaryVehicleMode();
    }

    @Override
    public OffsetDateTime value6() {
        return getValidityStart();
    }

    @Override
    public OffsetDateTime value7() {
        return getValidityEnd();
    }

    @Override
    public Integer value8() {
        return getPriority();
    }

    @Override
    public String value9() {
        return getLabel();
    }

    @Override
    public LineRecord value1(UUID value) {
        setLineId(value);
        return this;
    }

    @Override
    public LineRecord value2(String value) {
        setNameI18n(value);
        return this;
    }

    @Override
    public LineRecord value3(String value) {
        setShortNameI18n(value);
        return this;
    }

    @Override
    public LineRecord value4(String value) {
        setDescriptionI18n(value);
        return this;
    }

    @Override
    public LineRecord value5(String value) {
        setPrimaryVehicleMode(value);
        return this;
    }

    @Override
    public LineRecord value6(OffsetDateTime value) {
        setValidityStart(value);
        return this;
    }

    @Override
    public LineRecord value7(OffsetDateTime value) {
        setValidityEnd(value);
        return this;
    }

    @Override
    public LineRecord value8(Integer value) {
        setPriority(value);
        return this;
    }

    @Override
    public LineRecord value9(String value) {
        setLabel(value);
        return this;
    }

    @Override
    public LineRecord values(UUID value1, String value2, String value3, String value4, String value5, OffsetDateTime value6, OffsetDateTime value7, Integer value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LineRecord
     */
    public LineRecord() {
        super(Line.LINE);
    }

    /**
     * Create a detached, initialised LineRecord
     */
    public LineRecord(UUID lineId, String nameI18n, String shortNameI18n, String descriptionI18n, String primaryVehicleMode, OffsetDateTime validityStart, OffsetDateTime validityEnd, Integer priority, String label) {
        super(Line.LINE);

        setLineId(lineId);
        setNameI18n(nameI18n);
        setShortNameI18n(shortNameI18n);
        setDescriptionI18n(descriptionI18n);
        setPrimaryVehicleMode(primaryVehicleMode);
        setValidityStart(validityStart);
        setValidityEnd(validityEnd);
        setPriority(priority);
        setLabel(label);
    }
}
