/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.deleted.routines;


import fi.hsl.jore.jore4.jooq.deleted.Deleted;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.Record;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;



/**
 * @deprecated Unknown data type. Please define an explicit {@link
 * org.jooq.Binding} to specify how this type should be handled. Deprecation can
 * be turned off using {@literal <deprecationOnUnknownTypes/>} in your code
 * generator configuration.
 */
@Deprecated
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RouteShape_1660903023968 extends AbstractRoutine<Object> {

    private static final long serialVersionUID = 1L;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static final Parameter<Object> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geography\""), false, false);

    /**
     * The parameter <code>deleted.route_shape_1660903023968.route_row</code>.
     */
    public static final Parameter<Record> ROUTE_ROW = Internal.createParameter("route_row", fi.hsl.jore.jore4.jooq.route.tables.Route.ROUTE_.getDataType(), false, false);

    /**
     * Create a new routine call instance
     */
    public RouteShape_1660903023968() {
        super("route_shape_1660903023968", Deleted.DELETED, org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geography\""));

        setReturnParameter(RETURN_VALUE);
        addInParameter(ROUTE_ROW);
    }

    /**
     * Set the <code>route_row</code> parameter IN value to the routine
     */
    public void setRouteRow(Record value) {
        setValue(ROUTE_ROW, value);
    }

    /**
     * Set the <code>route_row</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    public void setRouteRow(Field<Record> field) {
        setField(ROUTE_ROW, field);
    }
}
