/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.importer.jooq.network.tables.records;


import fi.hsl.jore.importer.jooq.network.tables.NetworkRouteStopPointsStaging;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NetworkRouteStopPointsStagingRecord extends UpdatableRecordImpl<NetworkRouteStopPointsStagingRecord> implements Record4<String, Integer, Boolean, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>network.network_route_stop_points_staging.network_route_stop_point_ext_id</code>.
     */
    public void setNetworkRouteStopPointExtId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>network.network_route_stop_points_staging.network_route_stop_point_ext_id</code>.
     */
    public String getNetworkRouteStopPointExtId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>network.network_route_stop_points_staging.network_route_stop_point_order</code>.
     */
    public void setNetworkRouteStopPointOrder(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>network.network_route_stop_points_staging.network_route_stop_point_order</code>.
     */
    public Integer getNetworkRouteStopPointOrder() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>network.network_route_stop_points_staging.network_route_stop_point_hastus_point</code>.
     */
    public void setNetworkRouteStopPointHastusPoint(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>network.network_route_stop_points_staging.network_route_stop_point_hastus_point</code>.
     */
    public Boolean getNetworkRouteStopPointHastusPoint() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>network.network_route_stop_points_staging.network_route_stop_point_timetable_column</code>.
     */
    public void setNetworkRouteStopPointTimetableColumn(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>network.network_route_stop_points_staging.network_route_stop_point_timetable_column</code>.
     */
    public Integer getNetworkRouteStopPointTimetableColumn() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, Integer, Boolean, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, Integer, Boolean, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return NetworkRouteStopPointsStaging.NETWORK_ROUTE_STOP_POINTS_STAGING.NETWORK_ROUTE_STOP_POINT_EXT_ID;
    }

    @Override
    public Field<Integer> field2() {
        return NetworkRouteStopPointsStaging.NETWORK_ROUTE_STOP_POINTS_STAGING.NETWORK_ROUTE_STOP_POINT_ORDER;
    }

    @Override
    public Field<Boolean> field3() {
        return NetworkRouteStopPointsStaging.NETWORK_ROUTE_STOP_POINTS_STAGING.NETWORK_ROUTE_STOP_POINT_HASTUS_POINT;
    }

    @Override
    public Field<Integer> field4() {
        return NetworkRouteStopPointsStaging.NETWORK_ROUTE_STOP_POINTS_STAGING.NETWORK_ROUTE_STOP_POINT_TIMETABLE_COLUMN;
    }

    @Override
    public String component1() {
        return getNetworkRouteStopPointExtId();
    }

    @Override
    public Integer component2() {
        return getNetworkRouteStopPointOrder();
    }

    @Override
    public Boolean component3() {
        return getNetworkRouteStopPointHastusPoint();
    }

    @Override
    public Integer component4() {
        return getNetworkRouteStopPointTimetableColumn();
    }

    @Override
    public String value1() {
        return getNetworkRouteStopPointExtId();
    }

    @Override
    public Integer value2() {
        return getNetworkRouteStopPointOrder();
    }

    @Override
    public Boolean value3() {
        return getNetworkRouteStopPointHastusPoint();
    }

    @Override
    public Integer value4() {
        return getNetworkRouteStopPointTimetableColumn();
    }

    @Override
    public NetworkRouteStopPointsStagingRecord value1(String value) {
        setNetworkRouteStopPointExtId(value);
        return this;
    }

    @Override
    public NetworkRouteStopPointsStagingRecord value2(Integer value) {
        setNetworkRouteStopPointOrder(value);
        return this;
    }

    @Override
    public NetworkRouteStopPointsStagingRecord value3(Boolean value) {
        setNetworkRouteStopPointHastusPoint(value);
        return this;
    }

    @Override
    public NetworkRouteStopPointsStagingRecord value4(Integer value) {
        setNetworkRouteStopPointTimetableColumn(value);
        return this;
    }

    @Override
    public NetworkRouteStopPointsStagingRecord values(String value1, Integer value2, Boolean value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NetworkRouteStopPointsStagingRecord
     */
    public NetworkRouteStopPointsStagingRecord() {
        super(NetworkRouteStopPointsStaging.NETWORK_ROUTE_STOP_POINTS_STAGING);
    }

    /**
     * Create a detached, initialised NetworkRouteStopPointsStagingRecord
     */
    public NetworkRouteStopPointsStagingRecord(String networkRouteStopPointExtId, Integer networkRouteStopPointOrder, Boolean networkRouteStopPointHastusPoint, Integer networkRouteStopPointTimetableColumn) {
        super(NetworkRouteStopPointsStaging.NETWORK_ROUTE_STOP_POINTS_STAGING);

        setNetworkRouteStopPointExtId(networkRouteStopPointExtId);
        setNetworkRouteStopPointOrder(networkRouteStopPointOrder);
        setNetworkRouteStopPointHastusPoint(networkRouteStopPointHastusPoint);
        setNetworkRouteStopPointTimetableColumn(networkRouteStopPointTimetableColumn);
    }
}
