/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.importer.jooq.network.tables.records;


import fi.hsl.jore.importer.config.jooq.converter.time_range.TimeRange;
import fi.hsl.jore.importer.jooq.network.tables.NetworkRouteStopPointsHistory;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NetworkRouteStopPointsHistoryRecord extends TableRecordImpl<NetworkRouteStopPointsHistoryRecord> implements Record6<UUID, String, Integer, Boolean, Integer, TimeRange> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>network.network_route_stop_points_history.network_route_point_id</code>.
     */
    public void setNetworkRoutePointId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>network.network_route_stop_points_history.network_route_point_id</code>.
     */
    public UUID getNetworkRoutePointId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>network.network_route_stop_points_history.network_route_stop_point_ext_id</code>.
     */
    public void setNetworkRouteStopPointExtId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>network.network_route_stop_points_history.network_route_stop_point_ext_id</code>.
     */
    public String getNetworkRouteStopPointExtId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>network.network_route_stop_points_history.network_route_stop_point_order</code>.
     */
    public void setNetworkRouteStopPointOrder(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>network.network_route_stop_points_history.network_route_stop_point_order</code>.
     */
    public Integer getNetworkRouteStopPointOrder() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>network.network_route_stop_points_history.network_route_stop_point_hastus_point</code>.
     */
    public void setNetworkRouteStopPointHastusPoint(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>network.network_route_stop_points_history.network_route_stop_point_hastus_point</code>.
     */
    public Boolean getNetworkRouteStopPointHastusPoint() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>network.network_route_stop_points_history.network_route_stop_point_timetable_column</code>.
     */
    public void setNetworkRouteStopPointTimetableColumn(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>network.network_route_stop_points_history.network_route_stop_point_timetable_column</code>.
     */
    public Integer getNetworkRouteStopPointTimetableColumn() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>network.network_route_stop_points_history.network_route_stop_point_sys_period</code>.
     */
    public void setNetworkRouteStopPointSysPeriod(TimeRange value) {
        set(5, value);
    }

    /**
     * Getter for <code>network.network_route_stop_points_history.network_route_stop_point_sys_period</code>.
     */
    public TimeRange getNetworkRouteStopPointSysPeriod() {
        return (TimeRange) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, String, Integer, Boolean, Integer, TimeRange> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, String, Integer, Boolean, Integer, TimeRange> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return NetworkRouteStopPointsHistory.NETWORK_ROUTE_STOP_POINTS_HISTORY.NETWORK_ROUTE_POINT_ID;
    }

    @Override
    public Field<String> field2() {
        return NetworkRouteStopPointsHistory.NETWORK_ROUTE_STOP_POINTS_HISTORY.NETWORK_ROUTE_STOP_POINT_EXT_ID;
    }

    @Override
    public Field<Integer> field3() {
        return NetworkRouteStopPointsHistory.NETWORK_ROUTE_STOP_POINTS_HISTORY.NETWORK_ROUTE_STOP_POINT_ORDER;
    }

    @Override
    public Field<Boolean> field4() {
        return NetworkRouteStopPointsHistory.NETWORK_ROUTE_STOP_POINTS_HISTORY.NETWORK_ROUTE_STOP_POINT_HASTUS_POINT;
    }

    @Override
    public Field<Integer> field5() {
        return NetworkRouteStopPointsHistory.NETWORK_ROUTE_STOP_POINTS_HISTORY.NETWORK_ROUTE_STOP_POINT_TIMETABLE_COLUMN;
    }

    @Override
    public Field<TimeRange> field6() {
        return NetworkRouteStopPointsHistory.NETWORK_ROUTE_STOP_POINTS_HISTORY.NETWORK_ROUTE_STOP_POINT_SYS_PERIOD;
    }

    @Override
    public UUID component1() {
        return getNetworkRoutePointId();
    }

    @Override
    public String component2() {
        return getNetworkRouteStopPointExtId();
    }

    @Override
    public Integer component3() {
        return getNetworkRouteStopPointOrder();
    }

    @Override
    public Boolean component4() {
        return getNetworkRouteStopPointHastusPoint();
    }

    @Override
    public Integer component5() {
        return getNetworkRouteStopPointTimetableColumn();
    }

    @Override
    public TimeRange component6() {
        return getNetworkRouteStopPointSysPeriod();
    }

    @Override
    public UUID value1() {
        return getNetworkRoutePointId();
    }

    @Override
    public String value2() {
        return getNetworkRouteStopPointExtId();
    }

    @Override
    public Integer value3() {
        return getNetworkRouteStopPointOrder();
    }

    @Override
    public Boolean value4() {
        return getNetworkRouteStopPointHastusPoint();
    }

    @Override
    public Integer value5() {
        return getNetworkRouteStopPointTimetableColumn();
    }

    @Override
    public TimeRange value6() {
        return getNetworkRouteStopPointSysPeriod();
    }

    @Override
    public NetworkRouteStopPointsHistoryRecord value1(UUID value) {
        setNetworkRoutePointId(value);
        return this;
    }

    @Override
    public NetworkRouteStopPointsHistoryRecord value2(String value) {
        setNetworkRouteStopPointExtId(value);
        return this;
    }

    @Override
    public NetworkRouteStopPointsHistoryRecord value3(Integer value) {
        setNetworkRouteStopPointOrder(value);
        return this;
    }

    @Override
    public NetworkRouteStopPointsHistoryRecord value4(Boolean value) {
        setNetworkRouteStopPointHastusPoint(value);
        return this;
    }

    @Override
    public NetworkRouteStopPointsHistoryRecord value5(Integer value) {
        setNetworkRouteStopPointTimetableColumn(value);
        return this;
    }

    @Override
    public NetworkRouteStopPointsHistoryRecord value6(TimeRange value) {
        setNetworkRouteStopPointSysPeriod(value);
        return this;
    }

    @Override
    public NetworkRouteStopPointsHistoryRecord values(UUID value1, String value2, Integer value3, Boolean value4, Integer value5, TimeRange value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NetworkRouteStopPointsHistoryRecord
     */
    public NetworkRouteStopPointsHistoryRecord() {
        super(NetworkRouteStopPointsHistory.NETWORK_ROUTE_STOP_POINTS_HISTORY);
    }

    /**
     * Create a detached, initialised NetworkRouteStopPointsHistoryRecord
     */
    public NetworkRouteStopPointsHistoryRecord(UUID networkRoutePointId, String networkRouteStopPointExtId, Integer networkRouteStopPointOrder, Boolean networkRouteStopPointHastusPoint, Integer networkRouteStopPointTimetableColumn, TimeRange networkRouteStopPointSysPeriod) {
        super(NetworkRouteStopPointsHistory.NETWORK_ROUTE_STOP_POINTS_HISTORY);

        setNetworkRoutePointId(networkRoutePointId);
        setNetworkRouteStopPointExtId(networkRouteStopPointExtId);
        setNetworkRouteStopPointOrder(networkRouteStopPointOrder);
        setNetworkRouteStopPointHastusPoint(networkRouteStopPointHastusPoint);
        setNetworkRouteStopPointTimetableColumn(networkRouteStopPointTimetableColumn);
        setNetworkRouteStopPointSysPeriod(networkRouteStopPointSysPeriod);
    }
}
