/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.importer.jooq.network.tables.records;


import fi.hsl.jore.importer.config.jooq.converter.time_range.TimeRange;
import fi.hsl.jore.importer.jooq.network.tables.ScheduledStopPointsHistory;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScheduledStopPointsHistoryRecord extends TableRecordImpl<ScheduledStopPointsHistoryRecord> implements Record5<UUID, String, UUID, JSONB, TimeRange> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>network.scheduled_stop_points_history.scheduled_stop_point_id</code>.
     */
    public void setScheduledStopPointId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>network.scheduled_stop_points_history.scheduled_stop_point_id</code>.
     */
    public UUID getScheduledStopPointId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>network.scheduled_stop_points_history.scheduled_stop_point_ext_id</code>.
     */
    public void setScheduledStopPointExtId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>network.scheduled_stop_points_history.scheduled_stop_point_ext_id</code>.
     */
    public String getScheduledStopPointExtId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>network.scheduled_stop_points_history.infrastructure_node_id</code>.
     */
    public void setInfrastructureNodeId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>network.scheduled_stop_points_history.infrastructure_node_id</code>.
     */
    public UUID getInfrastructureNodeId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>network.scheduled_stop_points_history.scheduled_stop_point_name</code>.
     */
    public void setScheduledStopPointName(JSONB value) {
        set(3, value);
    }

    /**
     * Getter for <code>network.scheduled_stop_points_history.scheduled_stop_point_name</code>.
     */
    public JSONB getScheduledStopPointName() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>network.scheduled_stop_points_history.scheduled_stop_point_sys_period</code>.
     */
    public void setScheduledStopPointSysPeriod(TimeRange value) {
        set(4, value);
    }

    /**
     * Getter for <code>network.scheduled_stop_points_history.scheduled_stop_point_sys_period</code>.
     */
    public TimeRange getScheduledStopPointSysPeriod() {
        return (TimeRange) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, String, UUID, JSONB, TimeRange> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UUID, String, UUID, JSONB, TimeRange> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return ScheduledStopPointsHistory.SCHEDULED_STOP_POINTS_HISTORY.SCHEDULED_STOP_POINT_ID;
    }

    @Override
    public Field<String> field2() {
        return ScheduledStopPointsHistory.SCHEDULED_STOP_POINTS_HISTORY.SCHEDULED_STOP_POINT_EXT_ID;
    }

    @Override
    public Field<UUID> field3() {
        return ScheduledStopPointsHistory.SCHEDULED_STOP_POINTS_HISTORY.INFRASTRUCTURE_NODE_ID;
    }

    @Override
    public Field<JSONB> field4() {
        return ScheduledStopPointsHistory.SCHEDULED_STOP_POINTS_HISTORY.SCHEDULED_STOP_POINT_NAME;
    }

    @Override
    public Field<TimeRange> field5() {
        return ScheduledStopPointsHistory.SCHEDULED_STOP_POINTS_HISTORY.SCHEDULED_STOP_POINT_SYS_PERIOD;
    }

    @Override
    public UUID component1() {
        return getScheduledStopPointId();
    }

    @Override
    public String component2() {
        return getScheduledStopPointExtId();
    }

    @Override
    public UUID component3() {
        return getInfrastructureNodeId();
    }

    @Override
    public JSONB component4() {
        return getScheduledStopPointName();
    }

    @Override
    public TimeRange component5() {
        return getScheduledStopPointSysPeriod();
    }

    @Override
    public UUID value1() {
        return getScheduledStopPointId();
    }

    @Override
    public String value2() {
        return getScheduledStopPointExtId();
    }

    @Override
    public UUID value3() {
        return getInfrastructureNodeId();
    }

    @Override
    public JSONB value4() {
        return getScheduledStopPointName();
    }

    @Override
    public TimeRange value5() {
        return getScheduledStopPointSysPeriod();
    }

    @Override
    public ScheduledStopPointsHistoryRecord value1(UUID value) {
        setScheduledStopPointId(value);
        return this;
    }

    @Override
    public ScheduledStopPointsHistoryRecord value2(String value) {
        setScheduledStopPointExtId(value);
        return this;
    }

    @Override
    public ScheduledStopPointsHistoryRecord value3(UUID value) {
        setInfrastructureNodeId(value);
        return this;
    }

    @Override
    public ScheduledStopPointsHistoryRecord value4(JSONB value) {
        setScheduledStopPointName(value);
        return this;
    }

    @Override
    public ScheduledStopPointsHistoryRecord value5(TimeRange value) {
        setScheduledStopPointSysPeriod(value);
        return this;
    }

    @Override
    public ScheduledStopPointsHistoryRecord values(UUID value1, String value2, UUID value3, JSONB value4, TimeRange value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScheduledStopPointsHistoryRecord
     */
    public ScheduledStopPointsHistoryRecord() {
        super(ScheduledStopPointsHistory.SCHEDULED_STOP_POINTS_HISTORY);
    }

    /**
     * Create a detached, initialised ScheduledStopPointsHistoryRecord
     */
    public ScheduledStopPointsHistoryRecord(UUID scheduledStopPointId, String scheduledStopPointExtId, UUID infrastructureNodeId, JSONB scheduledStopPointName, TimeRange scheduledStopPointSysPeriod) {
        super(ScheduledStopPointsHistory.SCHEDULED_STOP_POINTS_HISTORY);

        setScheduledStopPointId(scheduledStopPointId);
        setScheduledStopPointExtId(scheduledStopPointExtId);
        setInfrastructureNodeId(infrastructureNodeId);
        setScheduledStopPointName(scheduledStopPointName);
        setScheduledStopPointSysPeriod(scheduledStopPointSysPeriod);
    }
}
