/*
 * This file is generated by jOOQ.
 */
package fi.hsl.jore.jore4.jooq.internal_utils;


import fi.hsl.jore.jore4.jooq.DefaultCatalog;

import org.jooq.Catalog;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InternalUtils extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>internal_utils</code>
     */
    public static final InternalUtils INTERNAL_UTILS = new InternalUtils();

    /**
     * No further instances allowed
     */
    private InternalUtils() {
        super("internal_utils", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }
}
