TRUNCATE TABLE jr_linkki
TRUNCATE TABLE jr_solmu
TRUNCATE TABLE jr_piste
TRUNCATE TABLE jr_linja
TRUNCATE TABLE jr_linjannimet
TRUNCATE TABLE jr_reitti
TRUNCATE TABLE jr_reitinsuunta
TRUNCATE TABLE jr_reitinlinkki
TRUNCATE TABLE jr_pysakki