name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start test environment in the background
        run: docker-compose -f ./docker/docker-compose.test.yml up -d

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Verify test environment is up
        # We depend on both PostgreSQL and MS SQL, but the latter is the slow one
        run: |
          ./docker/wait-for-it.sh --host=localhost --port=17001
          sleep 5s

      - name: Build with Maven
        run: mvn --batch-mode verify
