name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start test environment in the background
        run: docker-compose up -d importer-test-destination-database importer-test-source-database

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Verify test environment is up
        uses: HSLdevcom/jore4-tools/github-actions/healthcheck@healthcheck-v1
        with:
          # We depend on both PostgreSQL and MS SQL, but the latter is the slow one
          command: "curl --fail http://localhost:17001 --output /dev/null --silent"

      - name: Run tests and try building a package
        run: mvn --batch-mode verify
