name: 'Spotless'
on:
  # this workflow is only called by others, won't be executed on itself
  workflow_call:

jobs:
  spotless:
    name: Check code is formatted with Spotless
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          java-package: jdk
          architecture: x64
          distribution: temurin
          cache: maven

      - name: Run Spotless Check
        run: mvn spotless:check
