name: Test whether the dockerized version works

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test-docker-compose:
    name: verify docker-compose setup
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start dependencies and importer application
        run: ./development.sh start

      - name: Verify that dockerized Importer API is up and running
        uses: HSLdevcom/jore4-tools/github-actions/healthcheck@healthcheck-v1
        with:
          command: "curl --fail http://localhost:3004/actuator/health --output /dev/null --silent"
          retries: 50
